### ISSUE TITLE
Multiple pages?

### ISSUE THREAD

**Issue by bguiz** [jxnblk/static-react#3]
I haven't tried this yet , because 

`static-react components/Root.js > index.html`

(as mentioned [here](http://jxnblk.com/writing/posts/zero-configuration-react-static-site-generator/))

makes me feel that this only generates a single HTML page...

Can this project generate multiple pages across multiple directories,
like would be required to upload to gh-pages as a static site?

**Comment by webuniverseio** [comment]
:+1: I have the same question. For example https://github.com/iansinnott/react-static-webpack-plugin can use react-router to generate multiple pages.

**Comment by jxnblk** [comment]
As an intentional design decision, this doesn't support react-router. This can be run with multiple scripts (i.e. one per page), but I wouldn't recommend it for more than five or so pages.

I might try to tackle routing with a different module, but don't plan on adding it in to this one.

**Comment by zebapy** [comment]
@jxnblk is it possible for this to simple generate multiple components? I don't want them connected via router. Instead, I'm trying to find a solution for writing emails in React
